#!/usr/bin/env python
from urllib2 import urlopen
from urllib import urlencode
import pipes
import sys
from gd import detect_lang

# The google translate API can be found here: 
# http://code.google.com/apis/ajaxlanguage/documentation/#Examples
argv = sys.argv
if len(argv) < 3:
	print 'USAGE:\n%s language_code text'%argv[0]
	print '%s language_code --file file_name'%argv[0]
	sys.exit(1)
if argv[2] == '--file':
	text = open(argv[3], 'r').read()
else: text=' '.join(argv[2:])

lang1= detect_lang(text) #sys.argv[2]
lang2=argv[1]
langpair='%s|%s'%(lang1,lang2)
base_url='http://ajax.googleapis.com/ajax/services/language/translate?'
params=urlencode( (('v',1.0),
                 ('q',text),
                 ('langpair',langpair),) )
url=base_url+params
content=urlopen(url).read()
start_idx=content.find('"translatedText":"')+18
translation=content[start_idx:]
end_idx=translation.find('"}, "')
translation=translation[:end_idx]
print translation  
